/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function F1Mclaren(props) {
  const group = useRef();
  const gltf = useLoader(GLTFLoader, "/f1mclaren/model/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} scale={0.8}>
      <primitive
        object={gltf.scene}
        position={[-1.37, -3.3, 0.65]}
        rotation={[-1.6, 0, 0.02]}
      />
    </group>
  );
}
